run:
  timeout: 10m

linters:
  enable-all: true
  disable:
    - exhaustivestruct # deprecated
    - interfacer # deprecated
    - varcheck # deprecated
    - nosnakecase # deprecated
    - ifshort # deprecated
    - maligned # deprecated
    - deadcode # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - golint # deprecated
    - rowserrcheck # deprecated
    - sqlclosecheck # deprecated
    - wastedassign # deprecated
    - varnamelen # useless
    - paralleltest # false positive
    - tparallel # false positive
    - tagliatelle # Breaking: 'Rule' tag -> 'rule'

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - exhaustivestruct
        - exhaustruct

linters-settings:
  cyclop:
    max-complexity: 11
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
